### PR TITLE
Added creation of sub-directories based on mpd structure

### PR DESCRIPTION
**Pull request by isaiah1112**
Kept running into an error when Representations require their own sub-directories. This fixes those errors.

### CODE REVIEW

**Comment by przemyslaw-gorszkowski-red** [comment]
Does it create all subdirectories? If not please take a look on my commit: https://github.com/przemyslaw-gorszkowski-red/dash-proxy/commit/eeeab584b48df8b46582281800c363113454acf0

**Comment by isaiah1112** [comment]
> Does it create all subdirectories? If not please take a look on my commit: [przemyslaw-gorszkowski-red@eeeab58](https://github.com/przemyslaw-gorszkowski-red/dash-proxy/commit/eeeab584b48df8b46582281800c363113454acf0)

When using a command such as:
```
dash-proxy.py http://localhost:8000/channel-1/manifest.mpd -o ./
```
Where the MPD contains the following AdaptationSets and Representations:
* root_audio_video[0-2]
* root_audio0
* root_video[0-2]
This PR will create the following directories:
```
.
|- root_audio_video0
|- root_audio_video1
|- root_audio_video2
|- root_audio0
|- root_video0
|- root_video1
|- root_video2
```
Each of the directories will contain their respective `ts` files.  This does NOT create a top-level directory (i.e. `channel-1` from the URL above).

I will say I like that your commit does create a function for doing this.  If you submit a PR I'll close this one in favor of yours!

**Comment by przemyslaw-gorszkowski-red** [comment]
Ok, but what in case when the MPD contains the following AdaptationSets and Representations:

- some/more/sub/directories/root_audio_video[0-2]
...
?

In case of mine commit the "some","more","sub", "directories" will be also created.

**Comment by isaiah1112** [comment]
> Ok, but what in case when the MPD contains the following AdaptationSets and Representations:
> 
> * some/more/sub/directories/root_audio_video[0-2]
>   ...
>   ?
> 
> In case of mine commit the "some","more","sub", "directories" will be also created.

Do you have an example MPD?  Would be happy to test it!

**Comment by przemyslaw-gorszkowski-red** [comment]
I have, but I cannot share. I will try to find some example from public internet

**Comment by isaiah1112** [comment]
> I have, but I cannot share. I will try to find some example from public internet

Understood.  I'll spend some cycles to see if I can replicate one as well!

**Pull request closed without merging**
